#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_lux = env_modules.Clone()

print("ffwd: building...")

env_lux.add_source_files(env.modules_sources, "*.cpp")

SConscript("map/SCsub")
SConscript("physics/SCsub")
SConscript("io/SCsub")
SConscript("controller/SCsub")
