#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_lux = env_modules.Clone()

print("Building Fast Forward types...")

env_lux.add_source_files(env.modules_sources, "*.cpp")

SConscript("physics/SCsub")
